// Automatically generated by astro-icon
// 71783947e2ca4216d70fcd1f436c45d459206da7bc253e05cc6cba10ccb03db5

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "carbon:location"
		| "carbon:link"
		| "carbon:identification"
		| "carbon:construction"
		| "carbon:events-alt"
		| "carbon:education"
		| "carbon:tools"
		| "carbon:certificate"
		| "carbon:pen"
		| "carbon:volume-file-storage"
		| "carbon:document-pdf"
		| "carbon:location-person"
		| "carbon:moon"
		| "carbon:light"
		| "carbon:email"
		| "carbon:logo-github"
		| "carbon:logo-linkedin"
		| "mdi:telegram"
		| "mdi:laptop-account";
}