// Automatically generated by astro-icon
// 961841430b8a4c243fbb8ba1a5aa9b1c52df281c52860dd1229ec4631ca46389

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "carbon:location"
		| "carbon:link"
		| "carbon:identification"
		| "carbon:construction"
		| "carbon:events-alt"
		| "carbon:education"
		| "carbon:tools"
		| "carbon:certificate"
		| "carbon:pen"
		| "carbon:volume-file-storage"
		| "carbon:document-pdf"
		| "carbon:location-person"
		| "carbon:moon"
		| "carbon:light"
		| "carbon:email"
		| "carbon:logo-github"
		| "carbon:logo-linkedin"
		| "mdi:telegram";
}