// Automatically generated by astro-icon
// c31b3306481a9bfebad48c19c8935bb4b46a6b53df4dda286455aa0e54cf5af2

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "carbon:location"
		| "carbon:link"
		| "carbon:identification"
		| "carbon:construction"
		| "carbon:education"
		| "carbon:tools"
		| "carbon:certificate"
		| "carbon:pen"
		| "carbon:volume-file-storage"
		| "carbon:document-pdf"
		| "carbon:location-person"
		| "carbon:moon"
		| "carbon:light"
		| "carbon:email"
		| "carbon:logo-github"
		| "carbon:logo-linkedin"
		| "mdi:telegram";
}